apiVersion: v1
kind: Service
metadata:
  name: axonserver
  labels:
    app: axonserver
spec:
  ports:
    - port: 8124
      name: grpc
      targetPort: 8124
  # Headless service - Sometimes you don’t need load-balancing and a single Service IP. In this case, you can create what are termed “headless” Services, by explicitly specifying "None" for the cluster IP (.spec.clusterIP).
  clusterIP: None
  selector:
    app: axonserver
---
apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  labels:
    app: axonserver
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8024"
spec:
  type: ClusterIP
  ports:
    - port: 8024
      name: gui
      targetPort: 8024
  # If you want to make sure that connections from a particular client are passed to the same Pod each time, you can select the session affinity based on the client’s IP addresses by setting service.spec.sessionAffinity to “ClientIP” (the default is “None”).
  sessionAffinity: ClientIP
  selector:
    app: axonserver
